### ISSUE TITLE
Http2 Agent

### ISSUE THREAD

**Issue by yovanoc** [TooTallNate/proxy-agents#107]
Hello, not a real issue sorry, just a question.

I found this issue on got: https://github.com/sindresorhus/got/issues/1265

And wanted to know, have you planned to do an http2 agent?

**Comment by yovanoc** [comment]
I think we can look forward to this maybe

```ts
import http2 from "http2-wrapper";

class MyAgent extends http2.Agent {
  createConnection(origin: string, options: any) {
    console.log(`Connecting to ${http2.Agent.normalizeOrigin(origin)}`);
    return http2.Agent.connect(origin, options);
  }
}
```

**Comment by yovanoc** [comment]
with this for websockets https://github.com/websockets/ws/issues/1458

**Comment by yovanoc** [comment]
Hello back @TooTallNate , we can financially support you for this if you want

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
