### ISSUE TITLE
Getting error SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by ellenaua** [TooTallNate/proxy-agents#116]
Getting error SELF_SIGNED_CERT_IN_CHAIN

**Comment by cdesch** [comment]
You probably need to include the CA cert.  This is most likely related to https://github.com/TooTallNate/node-https-proxy-agent/issues/54 and https://github.com/TooTallNate/node-https-proxy-agent/issues/89

**Comment by boly38** [comment]
Hi
It would be great to add to this agent support of `rejectUnauthorized: false,` (like in https.Agent cf. [Karthik answer](https://stackoverflow.com/questions/52478069/node-fetch-disable-ssl-verification))

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
