### ISSUE TITLE
Support of URL as constructor parameter (instead of legacy url)

### ISSUE THREAD

**Issue by AndreasAugustin** [TooTallNate/proxy-agents#117]
## Story

According to https://nodejs.org/api/url.html legacy `url` is deprecated and is replaced by the [WHATWG URL](https://nodejs.org/api/url.html#url_the_whatwg_url_api).

It would be nice if the constructor would also support this Object.

Because of the shallow clone on line `46` with the spread operator (Object.assign) within [src/agent.ts](https://github.com/TooTallNate/node-https-proxy-agent/blob/master/src/agent.ts)

```typescript
		const proxy: HttpsProxyAgentOptions = { ...opts };
```

According to my current tests it is currently not possible to use the `URL` object because the `Object.assign` is not working on that type. There is also a [StackOverflow](https://stackoverflow.com/questions/48232131/why-does-object-assign-not-copy-the-properties-of-a-url-object/48232173) thread about this.

`net.connect` is able to handle the `URL` object.

## Possible solution

Reading the `GitHub action` the minimum node version to support is `node6`. 
With this version the [WHATWG API](https://nodejs.org/docs/latest-v6.x/api/url.html#url_the_whatwg_url_api) was already supported. idea is to use something like

```typescript
const { URL } = require('url');
const proxy = new URL(opts.href);
```

instead of the shallow clone with the spread operator.

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
