### ISSUE TITLE
Module 'net' (+ others) has no default export error

### ISSUE THREAD

**Issue by pankleks** [TooTallNate/proxy-agents#120]
![image](https://user-images.githubusercontent.com/14176066/115534958-972d7700-a298-11eb-8e39-ac8b07589c37.png)

it can be fixed by changing `import * as net from "net";`

**Comment by pankleks** [comment]
it can be solved by adding `"allowSyntheticDefaultImports": true` in tsconfig.json

**Comment by TooTallNate** [comment]
> it can be fixed by changing `import * as net from "net";`

Pull request welcome!

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
