### ISSUE TITLE
Http-proxy-agent with Axios library, Https agent properties does not work

### ISSUE THREAD

**Issue by nikolaitn** [TooTallNate/proxy-agents#121]
Hi,
I am using Axios library (Typescript) for making a proxy request and for testing purposes I am using a self signed certificate and need to set 
in the agent  { rejectUnauthorized: false}, later need to setup a 'ca' and 'checkServerIdentity'.

If I put those like this: 

```
const httpProxyAgent = new HttpsProxyAgent({
            host: "",
            port: 999,
            rejectUnauthorized: false
        });

this.axios = Axios.create(
            {
                baseURL: url,
                timeout: 30000,
                headers: {
                    "Authorization": `Basic ####`
                },
                httpsAgent: httpProxyAgent
            }
        )
```

This doesn't seem to work, 'rejectUnauthorized' is set as a proxy parameter, which is not what we want, we want it as an agent options.
Does anyone knows how to use it properly with Axios?

**Comment by dscalzi** [comment]
workaround: https://github.com/TooTallNate/node-https-proxy-agent/issues/89

**Comment by jeromeSH26** [comment]
seems, workaround still not correct fom `rejectUnauthorized: false`
still got error `Error: unable to verify the first certificate` with Axios

```
import { ClientRequest, RequestOptions } from "agent-base";
import { HttpsProxyAgent, HttpsProxyAgentOptions } from "https-proxy-agent";
import { Socket } from "net";

class ClsHttpsProxyAgent extends HttpsProxyAgent {
  private ca: any;

  constructor(opts: HttpsProxyAgentOptions) {
    super(opts);
    this.ca = opts.ca;
  }

  async callback(req: ClientRequest, opts: RequestOptions): Promise<Socket> {
    return super.callback(req, Object.assign(opts, { ca: this.ca }));
  }
}

export { ClsHttpsProxyAgent };
```
```
const ops = {
      rejectUnauthorized: false,
      protocol: "http:",
      host: "a.b.c.d",
      hostname: "a.b.c.d",
      port: 8080,
      href: "http://a.b.c.d:8080",
      keepAlive: true,
    };

    const agent = new ClsHttpsProxyAgent(ops);

const a = await axios({
      method: "POST",
      url: this._authUrl,
      httpsAgent: agent,
      data: JSON.stringify({
        ldap_user: this._apigeeUsername,
        ldap_password: this._apigeePassword,
      }),
      headers: {
        "Content-Type": "application/json",
        "x-apigee-client-id": this._clientId,
        "x-apigee-client-secret": this._clientSecret,
      },
      proxy: false,
    });


```

**Comment by mbargiel** [comment]
For some reason I was also unable to use that workaround. The problems seems to stem from the decision to drop `this.options` [in the base class](https://github.com/TooTallNate/node-agent-base/commit/7e1a2da1915d6a0d2025bb4ba6148e39d6f4334a#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L104). This object would allow carrying the relevant TLS options to the `tls.connect` call.

Another TLS option that is sorely missing as a result is `ca`, in order to provide a custom CA configuration for the proxy itself. This basically made `https-proxy-agent` (and `http-proxy-agent` too - see below) unusable with proxies that use a custom certificate authority, in environments where we cannot use the `NODE_EXTRA_CA_CERTS` environment variable.

The `ca`, `servername` and `rejectUnauthorized` TLS options should be passed along, if specified. Or better yet... reinstate the `options` object. :smile:

Side-note, which might deserve its own Issue: I think `http-proxy-agent` and `https-proxy-agent` should be merged into a single class that picks the right implementation in its `callback` function - either it establishes a tunnel and uses that (https-proxy-agent code path), or it performs a straight request based on the original request options (http-proxy-agent code path).

**Comment by mbargiel** [comment]
OK after a bit of digging around, here's the conclusion:

1. The `ca` or `rejectUnauthorized` options passed to an `HttpsProxyAgent` constructor are only passed to the proxy socket connection. They are not passed to the `tls.connect` call that upgrades the proxy socket (net.Socket or tls.Socket) to a tls.Socket; only the request options are passed (mostly) verbatim to this `tls.connect` call.
2. Axios does not support the `ca` and `rejectUnauthorized` request options (unlike `https.request` - that's definitely a questionable choice). They can be passed through an agent instance.

1 + 2 = HttpsProxyAgent cannot be used to access an upstream server over HTTPS if `ca` or `rejectUnauthorized` needs to be used. 

I intend to open a PR to Axios to add `ca` and `rejectUnauthorized` support to its request options to fix 2) as well as open a PR here to fix 1).

**Comment by dscalzi** [comment]
maybe give https://github.com/delvedor/hpagent a try as well. The library is not abandoned like this one and it works very well with a lot of the libraries I use (ie aws-sdk, got, etc).

**Comment by mbargiel** [comment]
@dscalzi I looked at `hpagent` and it's very promising. Thank you! 

I easily replaced `https-proxy-agent` with it in my project, with the only caveat being that it doesn't support configuring the `ca` or `rejectUnauthorized` options for the proxy server connection - basically, the reverse problem of the above 😅  But that one is active (version 1.0.0 was released about a week ago) so there's hope that it can be fixed.

**Comment by dscalzi** [comment]
> @dscalzi I looked at `hpagent` and it's very promising. Thank you!
> 
> I easily replaced `https-proxy-agent` with it in my project, with the only caveat being that it doesn't support configuring the `ca` or `rejectUnauthorized` options for the proxy server connection - basically, the reverse problem of the above 😅 But that one is active (version 1.0.0 was released about a week ago) so there's hope that it can be fixed.

I have been able to configure the ca property with hpagent.

**Comment by mbargiel** [comment]
For the connection to the upstream URL, yes, not for the HTTP CONNECT
request to the proxy server (when proxying over HTTPS). Unless I missed
something? How did you do it?

Le jeu. 12 mai 2022 à 22:07, Daniel Scalzi ***@***.***> a
écrit :

**Comment by gguimond** [comment]
> For the connection to the upstream URL, yes, not for the HTTP CONNECT request to the proxy server (when proxying over HTTPS). Unless I missed something? How did you do it?

you can do it through proxyRequestOptions

`proxyRequestOptions: {
    ca: [fs.readFileSync('ca.crt'),],
    rejectUnauthorized: true,
  },`

**Comment by mbargiel** [comment]
@gguimond Yes 😁 https://github.com/delvedor/hpagent/pull/72

![image](https://user-images.githubusercontent.com/1649118/219714837-fd457d77-bbf4-4c8f-94e2-4178d9f49c11.png)

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
