### ISSUE TITLE
OPENSSL Certificate routine ERR_OSSL_X509_KEY_VALUES_MISMATCH

### ISSUE THREAD

**Issue by RSickenberg** [TooTallNate/proxy-agents#122]
Hello, 

I got an issue with Cypress (who uses your lib).
https://github.com/cypress-io/cypress-docker-images/issues/495

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
