### ISSUE TITLE
Types are incorrect?

### ISSUE THREAD

**Issue by Ed-Ed** [TooTallNate/proxy-agents#123]
Per the documentation, if I import the package and do the following:

```
import HttpsProxyAgent from 'https-proxy-agent';

const test = new HttpsProxyAgent(someVar)
```

I see the following TypeScript error:

```
(alias) function HttpsProxyAgent(opts: string | createHttpsProxyAgent.HttpsProxyAgentOptions): _HttpsProxyAgent
(alias) namespace HttpsProxyAgent
import HttpsProxyAgent
Only a void function can be called with the 'new' keyword.ts(2350)
```

**Comment by wong2** [comment]
+1

**Comment by JohnnyBill** [comment]
`import { HttpsProxyAgent } from 'https-proxy-agent';` maybe the correct way.
I tranformed my old javascript code that uses `const HttpsProxyAgent = require('https-proxy-agent');` to typescript and now i somehow get some strange ssl errors, that didnt happen before in the javascript version. Maybe there is some cornercases, where the import on top behaves different to the javascript version. I am really confused.

**Comment by TooTallNate** [comment]
In the latest release, there is no longer a default export. You should import like this:

```ts
import { HttpsProxyAgent } from 'https-proxy-agent';
```
