### ISSUE TITLE
Stuck when pipe or request.write()

### ISSUE THREAD

**Issue by Fosper** [TooTallNate/proxy-agents#124]
const fs = require('fs');
const url = require('url');
const https = require('https');
const HttpsProxyAgent = require('https-proxy-agent');

let requestOptions = url.parse('https://127.0.0.1');

requestOptions.method = 'POST';
requestOptions.agent = new HttpsProxyAgent('https://127.0.0.1:3000'); // <--- If comment this - all works fine.

let request = https.request(requestOption, (res) => {
    res.pipe(process.stdout);
});

fs.createReadStream(__dirname + '/test.txt').pipe(request); // <--- Didn't work. request.write('Hello') didn't work too. Just stuck.

// Working only request.end('Hello'), but sometimes i need send files and use Readable streams.
// p.s. socks-proxy-agent working very fine with request.write('Hello') and .pipe(request).
// p.s.s. 127.0.0.1 - just for example.

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
