### ISSUE TITLE
Sourcemaps cause warnings because src files are not included in distribution

### ISSUE THREAD

**Issue by gkjohnson** [TooTallNate/proxy-agents#125]
Hello! I'm seeing some warnings with Webpack source-map-loader when building a project with this project as a dependency because the src files are not included in the distribution but are referenced via the source maps:

```
WARNING in ./node_modules/https-proxy-agent/dist/parse-proxy-response.js
  Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
  Failed to parse source map from '<local path>/node_modules/https-proxy-agent/src/parse-proxy-response.ts' file: Error: ENOENT: no such file or directory, open '<local path>/node_modules/https-proxy-agent/src/parse-proxy-response.ts'
```

I believe adding the "src" folder to the [list of published files](https://github.com/TooTallNate/node-https-proxy-agent/blob/master/package.json#L7-L9) would fix this.

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
