### ISSUE TITLE
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by MaksimKiselev** [TooTallNate/proxy-agents#126]
After upgrade env to use node v16 I've got error: `TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"`

After small research I've found that problem in `agent-base` dependency and this already fixed: https://github.com/TooTallNate/node-agent-base/pull/47

Please update `agent-base` dependency.

**Comment by MaksimKiselev** [comment]
Workaround: install `agent-base` vesrsion upper 6.0.2 to root `npm i --save npm install agent-base@^6.0.2`

**Comment by ahmadyazdanii** [comment]
hi, i have this problem in node lts (14x)
please upgrade dependency

**Comment by yovanoc** [comment]
problem too with node 18

**Comment by yinxulai** [comment]
Even after installing to 6.0.2 there is still a problem

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.

**Comment by vamsideepak** [comment]
```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:399:5)
    at new ClientRequest (node:_http_client:189:11)
    at Object.request (node:http:98:10)
    at b.d 
    
    (C:\Users\XXXX\Desktop\MockServer\Trilogy_Client_Installer\workers\node_modules\node-downloader-helper\dist\index.js:1:6742)
    at b.a (C:\Users\XXXX\Desktop\MockServer\Trilogy_Client_Installer\workers\node_modules\node-downloader-helper\dist\index.js:1:6164)
```
Getting the above issue when I am trying to download files using node-downloader-helper 
I am using node 16.16.0 and  18.14.0 by using nvm

**Comment by TooTallNate** [comment]
@vamsideepak Please open a new issue, with more details please. Include the code you are trying, what kind of proxy you are connecting to, etc.
