### ISSUE TITLE
DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066

### ISSUE THREAD

**Issue by fbeauchamp** [TooTallNate/proxy-agents#127]
We use `https-proxy-agent` to connect to server with a self signed certificate using their ip . 

`tls.connect`  with such a servername shows this warning :`DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066` 

The servername should be removed only when using an ip address, as to not disable SNI when possible

thanks in advance.

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
