### ISSUE TITLE
Host header is not comply with rfc when CONNECT

### ISSUE THREAD

**Issue by maximium** [TooTallNate/proxy-agents#132]
Hello. Would you consider to remove [this condition](https://github.com/TooTallNate/node-https-proxy-agent/blob/c30a9dc75a272591a80b9b4acef1496f80824f88/src/agent.ts#L115) and use connect target in the host header as is? Haproxy [enforces strict checking](https://github.com/haproxy/haproxy/commit/531b83e039bbe369e4fe6e775e9bfa310d780da1) of host header according to [rfc7230 section 5.4](https://datatracker.ietf.org/doc/html/rfc7230#section-5.4) and returns 400 response if there is no port in the host header.

> If the target URI includes an authority component, then a
> client MUST send a field-value for Host that is identical to that
> authority component, excluding any userinfo subcomponent and its "@"
> delimiter ([Section 2.7.1](https://datatracker.ietf.org/doc/html/rfc7230#section-2.7.1))

**Comment by maximium** [comment]
There is a [pull request](https://github.com/TooTallNate/node-https-proxy-agent/pull/133) if you'd like to accept my proposal.

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
