### ISSUE TITLE
[NOTE] A small note for all coder trying this package

### ISSUE THREAD

**Issue by 01101sam** [TooTallNate/proxy-agents#137]
This package is not maintained for some days.

If you want a bug-free and with SOCKS combined package, please try my package [@sam01101/node-proxy-agent](https://www.npmjs.com/package/@sam01101/node-proxy-agent).
`npm i @sam01101/node-proxy-agent`

Bug report & PR are welcome

BTW The author is working on another project [node-socks-proxy-agent](https://github.com/TooTallNate/node-socks-proxy-agent), most of the codes are taken from his repo.

P.S. Sorry for the ads but I think this is necessary to notice some of the users because of those bugs.

**Comment by TooTallNate** [comment]
This package has been revived! All the related packages have been modernized and moved into this repository as a monorepo, so the maintenance burden should be much lower at this point.
