### ISSUE TITLE
Is there a way to set connect pool on https-proxy-agent

### ISSUE THREAD

**Issue by yangliguo7** [TooTallNate/proxy-agents#141]
I use `http-proxy-middleware` to forward request

the  code like
```
createProxyMiddleware({
  target: "https://XXXX",
  changeOrigin: true,
  timeout: 5000,
  secure: false,
  agent: new HttpsProxyAgent({
    host: "XXXX",
    port: 8080,
  })
})
```
but i want to set connect pool like `https.agent`
```
// const agent = new https.Agent({ 
//   maxSockets: 100,
//   keepAlive: true,
// });
```
but i check the source code and document。I cant find anywhere can put the params

Is there a way to set connect pool on https-proxy-agent ？

thanks.

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.

**Comment by TooTallNate** [comment]
Btw, `keepAlive: true` is supported as of the latest release.
