### ISSUE TITLE
use proxy not from env

### ISSUE THREAD

**Issue by trim21** [TooTallNate/proxy-agents#161]
I'm trying to upgrade `ProxyAgent` from v5

> Which proxy is used for each HTTP request is determined by the [proxy-from-env](https://www.npmjs.com/package/proxy-from-env) module, so check its documentation for instructions on configuring your environment variables.

I have many agent and some of them don't need proxy, how can I manually set proxy agent without changing env now?

**Comment by TooTallNate** [comment]
I think https://github.com/TooTallNate/proxy-agents/pull/160 will solve your needs.

**Comment by TooTallNate** [comment]
Let me know if the `getProxyForUrl()` option in [`proxy-agent@6.2.0`](https://github.com/TooTallNate/proxy-agents/releases/tag/proxy-agent%406.2.0) solves your needs.

**Comment by trim21** [comment]
Yes, look fine
