### ISSUE TITLE
Should not throw exception about invalid header

### ISSUE THREAD

**Issue by youginil** [TooTallNate/proxy-agents#162]
https://github.com/TooTallNate/proxy-agents/blob/63adbcefdb4783cc67c0eb90200886b4064e8639/packages/https-proxy-agent/src/parse-proxy-response.ts#L74-L79

The exception cannot be caught, and it affects user program, I think ignoring it is a decent solution.

**Comment by realbillwong** [comment]
> https://github.com/TooTallNate/proxy-agents/blob/63adbcefdb4783cc67c0eb90200886b4064e8639/packages/https-proxy-agent/src/parse-proxy-response.ts#L74-L79
> 
> The exception cannot be caught, and it affects user program, I think ignoring it is a decent solution.

Hey, have you been able to find a way to catch the error?

**Comment by youginil** [comment]
@realbillwong Maybe this will helps you.
https://github.com/nodejs/node/issues/27711#issuecomment-494049324

**Comment by TooTallNate** [comment]
Should be fixed in [`https-proxy-agent@6.2.1`](https://github.com/TooTallNate/proxy-agents/releases/tag/https-proxy-agent%406.2.1).
