### ISSUE TITLE
Property 'emit' does not exist on type 'HttpsProxyAgent<Uri>'.

### ISSUE THREAD

**Issue by ttodua** [TooTallNate/proxy-agents#183]
this line: 
https://github.com/TooTallNate/proxy-agents/blob/main/packages/https-proxy-agent/src/index.ts#L138
throws an error when we use it in ts project:
 `error TS2339: Property 'emit' does not exist on type 'HttpsProxyAgent<Uri>'.`
do you know what should I do?

**Comment by TooTallNate** [comment]
You need to update `@types/node`.
