### ISSUE TITLE
Legacy word-wrap dependency causing ReDoS vulnevarilibies

### ISSUE THREAD

**Issue by jose-p-rivera** [TooTallNate/proxy-agents#201]
![image](https://github.com/TooTallNate/proxy-agents/assets/80977119/889ced6f-dbb7-44df-aadb-2a09b2e922f5)

this is affecting multiple packages that depend on proxy-agents such as puppeteer.

**Comment by TooTallNate** [comment]
Tracking possible fix [here](https://github.com/jonschlinkert/word-wrap/pull/33), but seems like the package is not being maintained.

**Comment by dikirill** [comment]
@TooTallNate please update optionator version, it has a fix already.

**Comment by elrob** [comment]
Are you able to update the `escodegen` used in `degenerator` to the latest? I think that will resolve the issue as `optionator` is no longer in the non-dev dependencies.
