### ISSUE TITLE
Issue with header parse buffer logic

### ISSUE THREAD

**Issue by byjrack** [TooTallNate/proxy-agents#207]
So was getting some exceptions after the move from 5.0.1 to 6.1.0 and traced it to the new header parsing

I was noticing that [headerParts](https://github.com/TooTallNate/proxy-agents/blob/main/packages/https-proxy-agent/src/parse-proxy-response.ts#L66) seemed to collect all the content in the proxy response and not just the headers.  In our case the 407 is accompanied by some HTML indicating the issue.

Looking at the code you grab endOfHeaders for building the buffer, but are not using it in the headerParts array creation.  In my case that means the content page gets included and then you start getting Invalid Header exceptions.

I have not tested this heavily, especially on really long responses that might require the "end of" recursive call, but should headerParts only use a slice of buffered?  

```
const headerParts = buffered.slice(0,endOfHeaders).toString('ascii').split('\r\n');
```

**Comment by TooTallNate** [comment]
Ya that seems like a bug. PR welcome!

**Comment by byjrack** [comment]
Cool I have a few internal gates to pass so may take a little bit even for a papercut, but hopefully shouldn't be stuck for long.  I also want to run through your contributing to make sure I can tick all the boxes.
