### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by ByFishh** [TooTallNate/proxy-agents#223]
Hi, when I use this simple code with the latest version of http-proxy-agent I got this error. I'm using React + typescript with Vite.

```
import { HttpProxyAgent } from 'http-proxy-agent';

const agent = new HttpProxyAgent('http://168.63.76.32:31
```

![image](https://github.com/TooTallNate/proxy-agents/assets/61200819/12ebc745-e38d-4e41-83c5-bae303c2806d)

**Comment by TooTallNate** [comment]
So this is code that is running on the browser?

**Comment by albertpratomo** [comment]
<img width="726" alt="image" src="https://github.com/TooTallNate/proxy-agents/assets/25815584/fa231906-8824-4055-bc12-83bc9ea649f5">

Hi, I also get the same error. Is this package not supposed to be used in browser?

**Comment by frama21** [comment]
yeah same like @albertpratomo issue,

**Comment by TooTallNate** [comment]
Correct, this package is meant to be used in Node.js code, not in the browser.
