### ISSUE TITLE
Cache Access Denied 

### ISSUE THREAD

**Issue by programerr01** [TooTallNate/proxy-agents#230]
When trying to use authenticated proxy server , it gives  `cache access denied`

`authenticate yourself`
the headers are taken from browser based automation from puppeter  for same proxy server 

but it's not working when used with http request with axios 
, the request looks like this 
   ```js
 const HttpsProxyAgent = require("https-proxy-agent");
 var axios = require("axios");

const httpsAgent = new HttpsProxyAgent({host: "url", port: "3120", auth: "username:password"})

var res = await axios('url',{headers,httpsAgent})
```

**Comment by TooTallNate** [comment]
Please pass a URL to the constructor instead, i.e. `http://username:password@url:3120`

More specifically, the property should not be `auth`, but instead `username` and `password` properties (which corresponds with the `URL` class).
