### ISSUE TITLE
Proxy connection ended before receiving CONNECT response

### ISSUE THREAD

**Issue by MANIMARAN-M** [TooTallNate/proxy-agents#233]
When I try to give proxy agent with Axios call getting the below error. 
Details:
Node JS application
Working in the client's VM
Trying to get details from JIRA cloud API

"message": "Proxy connection ended before receiving CONNECT response",
    "name": "Error",
    "stack": "Error: Proxy connection ended before receiving CONNECT response\n    at Socket.onend (P:\\beazley-base\\node_modules\\https-proxy-agent\\dist\\parse-proxy-response.js:32:20)\n    at Socket.emit (node:events:525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",

**Comment by TooTallNate** [comment]
Sounds like the proxy you are connecting to isn't working correctly, or is denying the connection based on the IP address of the client. This isn't an issue with this package.
