### ISSUE TITLE
critical security vulnerablility in dependency vm2

### ISSUE THREAD

**Issue by ctbaird** [TooTallNate/proxy-agents#240]
There is a critical security vulnerability in `vm2`, a dependency of  [degenerator](https://github.com/TooTallNate/proxy-agents/blob/8e92eb85e646c8873eee6e60c29e8e3518292746/packages/degenerator/package.json): 

```
vm2  *
Severity: critical
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-cchq-frgv-rjh5
fix available via `npm audit fix`
node_modules/vm2
  degenerator  3.0.0 - 4.0.4
  Depends on vulnerable versions of vm2
  node_modules/snowflake-sdk/node_modules/degenerator
```

`npm install` message warns that this package should not be used: 

```
npm WARN deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
```

There is also this issue with a notice from the maintainer: https://github.com/patriksimek/vm2/issues/533

**Comment by TooTallNate** [comment]
This was fixed in https://github.com/TooTallNate/proxy-agents/pull/224.
