### ISSUE TITLE
RequestError: Unexpected agent option: _events

### ISSUE THREAD

**Issue by JijaProGamer** [TooTallNate/proxy-agents#247]
This is the code:

`
got({
      url: "https://lumtest.com/myip.json",
      agent: this.extra.proxy ? new ProxyAgent({getProxyForUrl: () => this.extra.proxy}) : undefined
})
`

**Comment by lukekarrys** [comment]
This is an issue either how you are using the `got` library. Check the docs of that package for how to set the agent.
