### ISSUE TITLE
Move license information to separate file for packages

### ISSUE THREAD

**Issue by tschlechtweg** [TooTallNate/proxy-agents#250]
We parse the license information automatically for our product. Currently, the proxy-agents library we use (`https-proxy-agent`), has its LICENSE declaration inside the README. I would propose moving this declaration to a separate file for ease of parsing by using projects. If that is something you can agree on, I could also propose a PR.

**Comment by TooTallNate** [comment]
I'd accept a PR for this.

**Comment by tschlechtweg** [comment]
Done via #251.
