### ISSUE TITLE
Any method to listen for data on proxy server?

### ISSUE THREAD

**Issue by kaliubuntu0206** [TooTallNate/proxy-agents#257]
Hello.

I would like to know if there is any method to add listener to log data for `proxy` package.

Thanks.

**Comment by TooTallNate** [comment]
Which kind of data are you interested in? Are the debug logs sufficient? Try starting the proxy with the `DEBUG` env var set:

```
DEBUG=proxy:* proxy
```

**Comment by kaliubuntu0206** [comment]
@TooTallNate Would like to parse data chunk inside the socket received from the proxy server, how would it be possible? Where should I add the listener and concat those incoming data?
