### ISSUE TITLE
Can't set jar when createCookieAgent(httpProxyAgent.HttpProxyAgent) 

### ISSUE THREAD

**Issue by TenUchikawa** [TooTallNate/proxy-agents#261]
Can't set jar when createCookieAgent(httpProxyAgent.HttpProxyAgent) 

The type of the first argument is (string | URL) & CookieAgentOptions, so it cannot be assigned.
Shouldn't the type of the first argument be the following?
{
url:string|URL
}

```
const HttpProxyCookieAgent = createCookieAgent(httpProxyAgent.HttpProxyAgent);
const HttpsProxyCookieAgent = createCookieAgent(
  httpsProxyAgent.HttpsProxyAgent
);
//                       ↓
new HttpProxyCookieAgent({});
//                        ↓
new HttpsProxyCookieAgent({});
```

**Comment by lukekarrys** [comment]
`http-proxy-agent` should work with [`http-cookie-agent@>=5.0.4`](https://github.com/3846masa/http-cookie-agent/releases/tag/v5.0.4). The commit [implementing the changes](https://github.com/3846masa/http-cookie-agent/commit/e7d97dd50095b6183ab70661c401c2583fb352b9) have some examples of how this would work.
