### ISSUE TITLE
throw new Error('should not happen...')  its happening :(

### ISSUE THREAD

**Issue by gvuyk** [TooTallNate/proxy-agents#28]
The closest I've been to reproduce this is by overloading a proxy with requests, at some point the proxy just closes the connection and the app crashes with `Error: should not happen...`

**Comment by Diablohu** [comment]
![image](https://user-images.githubusercontent.com/1946774/29445812-544ef4a8-841b-11e7-937e-cc1c7a480c1f.png)

Same here :(

Windows 10
Node.js v7.8.0
NPM v5.3.0

**Comment by xxx-xyy** [comment]
me too

**Comment by Alster** [comment]
I confirm this. It definitely happens. 😄 

Windows 10
Node.js v7.10.0
NPM v5.8.0
https-proxy-agent v2.2.1

**Comment by GonyMaster** [comment]
me too

**Comment by k7eon** [comment]
me too :D

**Comment by monkeysuffrage** [comment]
Is it safe to just comment that out?
This is causing me some major problems.

**Comment by CodeingBoy** [comment]
Me too. It did happen. And I can't extract any information from the debug log.

**Comment by CodeingBoy** [comment]
> Me too. It did happen. And I can't extract any information from the debug log.

More info: I use npm with proxies created by privoxy. As I replaced privoxy with another proxy software, the problem disappeared. So privoxy may be related to this problem.

Environment:
- Windows 10 1809
- Privoxy 3.0.28
- Node.js v11.10.1
- npm 6.8.0

**Comment by planschmuh** [comment]
This happens to me as well, when I send many requests to a proxy. 

Environment:
- Windows 10 1809
- Node.js v11.10.1

**Comment by aborovsky** [comment]
This error occurs with more frequency if one use [nock](https://github.com/nock/nock) response mocking library.

**Comment by bytesmithing** [comment]
This error occurred when i execute the following code 
```
npm ci --cache-max=0 --no-save --https-proxy=http://127.0.0.1:1081 --proxy=http://127.0.0.1:1081
```

[2020-12-17T03_18_46_142Z-debug.log](https://github.com/TooTallNate/node-https-proxy-agent/files/5706801/2020-12-17T03_18_46_142Z-debug.log)

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
