### ISSUE TITLE
Proxy wont connect

### ISSUE THREAD

**Issue by TutorialMan7727** [TooTallNate/proxy-agents#319]
The following code wont connect to proxy. Proxy address is valid. (written in typescript)

import { Proxy, ProxyList } from "./proxyTypes";
import axios from "axios";
import { SocksProxyAgent } from "socks-proxy-agent";

const getProxys = async (): Promise<ProxyList> => {
  const proxyUrl: string =
    "https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc";
  return (await axios.get(proxyUrl)).data;
};

const getRandomProxy = (proxys: ProxyList): Proxy => {
  return proxys.data[Math.floor(Math.random() * proxys.data.length)];
};

const proxyToUri = (proxy: Proxy): string => {
  return `${proxy.protocols[0]}://${proxy.ip}:${proxy.port}`;
};

(async () => {
  const proxys = await getProxys();
  const proxy = getRandomProxy(proxys);
  const uri = proxyToUri(proxy);

  const httpsAgent = new SocksProxyAgent(uri);
  const client = axios.create({ httpsAgent });

  client.get("https://google.com/").then((res) => {
    console.log(res.data);
  });
})();

**Comment by lukekarrys** [comment]
@TutorialMan7727 Can you create a full reproduction in a gist or repo that can be cloned and run directly which shows the issue?

**Comment by TutorialMan7727** [comment]
https://github.com/TutorialMan7727/AAAAAAAAAA is a repo that contains the code
An example of an error is 
`socks4://94.139.169.250:5678 - 987ms
connect ECONNREFUSED 94.139.169.250:5678`

**Comment by TooTallNate** [comment]
That proxy server seems to not exist. You can't connect to it:

```
$ telnet 94.139.169.250 5678
Trying 94.139.169.250...
telnet: connect to address 94.139.169.250: Connection refused
telnet: Unable to connect to remote host
```

This doesn't seem to be an issue with this package.
