### ISSUE TITLE
Http headers

### ISSUE THREAD

**Issue by razbomi** [TooTallNate/proxy-agents#33]
Hey mate,

I noticed that when using the agent, if I have added header to the request they are not showing up in the webserver access logs. If I am reading the code correctly headers from the original request are not merged with the proxied request. Or am I doing something wrong???

If it is the case that headers from the original request should be merged in ... I'm happy to raise a pull request. :tada:

Cheers,
m

**Comment by TooTallNate** [comment]
Can you show some example code please?

**Comment by razbomi** [comment]
Ok some context ... I am constantly pained with a corporate proxy thing. We have a bunch of angular thingies so angular-cli is the flavour of the month here. Hence I am running `ng serve --proxy-config proxy.conf.js`. The code in `proxy.conf.js` is something along these lines.
```
const HttpsProxyAgent = require('https-proxy-agent');
const PROXY_CONFIG = [
  {
    agent: new HttpsProxyAgent(process.env.HTTPS_PROXY || process.env.HTTP_PROXY),
    context: [
      "/api",
      "/uat",
      "/meow"
    ],
    target:  {
      host: "my.awesome.api.com",
      protocol: "https:",
      port: 443
    },
    secure: false,
    changeOrigin: true,
    logLevel: "debug"
  }
]

module.exports = PROXY_CONFIG;
```
Now admittedly I haven't investigated properly what the angular cli thingie is actually doing with agent.

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
