### ISSUE TITLE
Virus Scanner is catching the pac-resolver/test/fixtures/gfw_whitelist.pac 

### ISSUE THREAD

**Issue by jangolano** [TooTallNate/proxy-agents#332]
Downloading the source code the pac-resolver/test/fixtures/gfw_whitelist.pac file is quarantined by my virus scanner (Avast).  It says the file contains the JS:ProxyBancos-DQ threat

**Comment by TooTallNate** [comment]
So this is when installing the package via npm? Or just when downloading the source code directly?

**Comment by jangolano** [comment]
Just when downloading the code.

**Comment by TooTallNate** [comment]
Ok, so in that case, I'm not too worried about it. You can allowlist the file in your virus scanner. These test files are not included in the published npm package, so would not be a problem for normal usage.
