### ISSUE TITLE
Remove unused debug dependency

### ISSUE THREAD

**Issue by alexparish** [TooTallNate/proxy-agents#358]
It seems the `debug` dependency in the `agent-base` package is no longer used. Can it be removed?

Happy to raise a PR for this.

**Comment by lukekarrys** [comment]
Please do! If you see any other cleanup stuff as well I'd be happy to see other PRs 😄 Running https://knip.dev on the repo might be interesting too 🤔

**Comment by alexparish** [comment]
Great minds... I actually ran knip and found `debug` but no other dependencies. There was a long list of unused devDependencies. I didn't go through them, but they could have been false positives.

PR for removing debug: https://github.com/TooTallNate/proxy-agents/pull/359
