### ISSUE TITLE
changing proxy tartget url based on the locale

### ISSUE THREAD

**Issue by rpmansion** [TooTallNate/proxy-agents#40]
I'm working on an app that has different servers per country and I want to target this by changing the proxy target URL based on the locale. For instance, for US-based users, I'm targeting the below.

```js
const proxyConfig = [
  {
    context: '/api',
    pathRewrite: { '^/api': '' },
    target: 'https://company.com',
    changeOrigin: true,
    secure: true
  }
];
```

For AU-based users, I'm targeting the below.

```js
const proxyConfig = [
  {
    context: '/api',
    pathRewrite: { '^/api': '' },
    target: 'https://company.com.au',
    changeOrigin: true,
    secure: true
  }
];
```

How do I do this by only changing the target to different URL based on locale?

**Comment by TooTallNate** [comment]
Looks like you are using the [`http-proxy`](https://github.com/http-party/node-http-proxy) module, so you should ask over there 😃
