### ISSUE TITLE
Support Windows Integrated Credentials with NTLM Proxy

### ISSUE THREAD

**Issue by ijabit** [TooTallNate/proxy-agents#44]
Git and NPM support this syntax: http://:@proxyserver:80
Instead of supplying a username:password before the @ symbol the username and password is left blank. This is great because obviously you don't want your real username and password in plain text in an npmrc file or environment variable. Is there any way to support that using this library?

**Comment by mindej** [comment]
+1

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
