### ISSUE TITLE
Deploy on Azure failed

### ISSUE THREAD

**Issue by ranouf** [TooTallNate/proxy-agents#47]
Hi,

I have a problem when I deploy my angular app with your package:

```
npm install
npm ERR! path D:\home\site\repository\src\client\node_modules.staging\npm-d4c06741\node_modules\libnpmhook\node_modules\npm-registry-fetch\node_modules\make-fetch-happen\node_modules\http-proxy-agent\node_modules\agent-base\node_modules\es6-promisify\node_modules\es6-promise
npm ERR! code EINVAL
npm ERR! errno -4071
npm ERR! syscall rename
npm ERR! EINVAL: invalid argument, rename 'D:\home\site\repository\src\client\node_modules.staging\npm-d4c06741\node_modules\libnpmhook\node_modules\npm-registry-fetch\node_modules\make-fetch-happen\node_modules\http-proxy-agent\node_modules\agent-base\node_modules\es6-promisify\node_modules\es6-promise' -> 'D:\home\site\repository\src\client\node_modules.staging\es6-promise-3ac93eae'
```

The problem is due to Azure who have issue to rename long path, Is there a way on your side to help me to fix this issue?

Probably not, but I tried so many different solutions which didnt work that now, I try other possibilities.

Thanks

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
