### ISSUE TITLE
Confused to use proxy-agent

### ISSUE THREAD

**Issue by PaykomanVll** [TooTallNate/proxy-agents#51]
Hello,

sorry for my bad english... I have build  a ws-server for my website (run over apache/nginx), now i need a way to accept clients (website users) that use an proxy. I think your proxy-agent is the solution, or?
Unfortunately, I can not get it started.

```js
var proxy = process.env.http_proxy || 'http://89.163.255.9:3128'; 
```

* `process.env.http_proxy`, is always undefined. why?
* What for ip/port i must set (i know not the port of nginx)?
* Why `http://`? I need only a https solution, my website can not be opened over `http://`...

```js
var endpoint = process.argv[2] || 'wss://mydomain.com:8080';
```

I know, our target is build a tunnel form client (website user) to webSocket-server, the endpoint is this server that i start now. 

I have some values tested, all get errors on the console.
`proxy-agent` works without changes on `nginx.conf`?
I hope you can help.

Greeting

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
