### ISSUE TITLE
Can I force HttpsProxyAgent to trust a certain certificate?

### ISSUE THREAD

**Issue by geajack** [TooTallNate/proxy-agents#54]
I want to use this module to pipe node-fetch requests through Fiddler for debugging. But when I try, I get an error about being unable to verify "the first certificate". This isn't unexpected, you get this with Firefox too - you have to export the cert from Fiddler as a .cer file and manually import it into Firefox. 

Can you import a .cer file into this module to do something similar? Is there a workaround?

**Comment by eigidi** [comment]
+1 to be able to set trusted CAs

**Comment by adefirmanf** [comment]
+1
Any update about this issue? @geajack

**Comment by geajack** [comment]
@adefirmanf  I think in the end I just gave up and used a different tool. Can't really remember, sorry.

**Comment by maslakov** [comment]
There are similar open issues and one workaround - https://github.com/TooTallNate/node-https-proxy-agent/issues/89

**Comment by cdesch** [comment]
+1

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
