### ISSUE TITLE
Improper Client Certificate Handling

### ISSUE THREAD

**Issue by larry011** [TooTallNate/proxy-agents#56]
Description: Currently, node-https-proxy-agent will forward client certificate used to authenticate against proxy to the backend server (being proxied by the proxy) as well. This would be undesirable behavior when both the site being proxied and the proxy itself enabled client certificate authentication, and they expect different client TLS certificates. I added backendOpts option to specify TLS options specifically for backend server.

 #55

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
