### ISSUE TITLE
NTLM Proxy authorization support for corporate proxy servers

### ISSUE THREAD

**Issue by mindej** [TooTallNate/proxy-agents#60]
Could you add example how to do NTLM proxy authorization.

**Comment by allisont** [comment]
@mindej , Have you had any luck making this work with an NTLM proxy ?. If so, would really appreciate if you could offer some guidance on this.

**Comment by mindej** [comment]
No, I have given up and installed http://cntlm.sourceforge.net/

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
