### ISSUE TITLE
Does not accept WHATWG URL

### ISSUE THREAD

**Issue by JonathanWilbur** [TooTallNate/proxy-agents#61]
This library does not accept WHATWG URLs. See this bug, which I have written up for one of this library's dependencies: https://github.com/TooTallNate/node-agent-base/issues/26. An additional bug writeup that may be instructive is https://github.com/nodejs/node/issues/26198.

You will also have this same issue with this line of code in this package:

```javascript
  var proxy = Object.assign({}, opts);
```

**Comment by sadasant** [comment]
@JonathanWilbur what do you think of this approach? https://github.com/TooTallNate/node-https-proxy-agent/pull/71

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
