### ISSUE TITLE
Problem when upgrading from Angular7 to Angular8

### ISSUE THREAD

**Issue by thomae82** [TooTallNate/proxy-agents#74]
Hi folks

I have updated my application from ANgular 7.2.9 to Angular 8.2.3. In our project we are using Win Auth. 

After the upgrade the login is not working any longer. No requests arrive at the backend.

Any idea or plans?

Cheers

Marc

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
