### ISSUE TITLE
hi bro, how to use with http2

### ISSUE THREAD

**Issue by gtsigner** [TooTallNate/proxy-agents#86]
I want to use in HTTP2 protocol agent, can you help me or give me a demo, I am looking for a long time

**Comment by zhaojunlike** [comment]
I can't find the interface in nodejs http2 document, and I can't find any information  ,  axios  or superagent all can't use http2 proxy

**Comment by zhaojunlike** [comment]
example:
```
const agent=new Agent("http://.....")
http2.request(url,agent)
```

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
