### ISSUE TITLE
Property 'options' is missing in type 'HttpsProxyAgent' but required in type 'Agent'.

### ISSUE THREAD

**Issue by marikaner** [TooTallNate/proxy-agents#98]
I am using the `HttpsProxyAgent` to set a proxy on axios requests in a TypeScript project.
I just tried to update to the newest version and got this error:
```
Property 'options' is missing in type 'HttpsProxyAgent' but required in type 'Agent'.
```

I checked your release notes and it seems that this is due to the fact, that `options` was removed from the underlying `Agent`, that mimics the `http.Agent` of node. In our case we are assigning the `HttpsProxyAgent` to a variable of type `https.Agent`.

Simplified example:
```
const agent: https.Agent = new HttpsProxyAgent('');
```

Can I avoid that?

I am currently investigating whether we can just use `http.Agent`, still, I am not sure whether it would be good practice to be compatible with the `https.Agent` type?

**Comment by marikaner** [comment]
I found out that we can just use the http.Agent. This might still be worth a consideration. Feel free to close though.

**Comment by FantasticFiasco** [comment]
This is problematic for me as well. I'm forced to stay on v4 instead of upgrading to v5.

Is there anything I can do to help? Was there a reason for removing `options`, or is it as simple are re-adding it again?

**Comment by zMrKrabz** [comment]
Here is a fix I made. 

```ts
import { Agent } from 'https';

const options: tunnel.ProxyOptions = {
  host: 'localhost',
  port: 8888
};

const client = got.extend({
  agent: {
    https: tunnel.httpsOverHttp({ proxy: options }) as Agent
  }
});
```
Note that I am using the got library as the example here, but essentially, I just casted the type. Not sure what implications this has, but so far, this is working fine for me.

**Comment by TooTallNate** [comment]
This module has gone through a large refactor and modernization. I am closing this issue as a bit of house cleaning. If you feel that this issue still exists in the latest release, feel free to open a new issue.
